apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  type: {{.Values.service.type}}
  selector:
    component: mongodb
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 27017 #service port - clusterIPport
      targetPort: 27017